spring:
  application:
    name: demo-spring-security

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${GOOGLE_CLIENT_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_CLIENT_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_CLIENT_TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: sub

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        boot.autoconfigure: ERROR
      springframework.security: DEBUG

server:
  port: 8080
  error:
    include-message: always